name: BlockyVending
version: 1.0
author: cryptohog
main: fi.blocky.blockyvending.bukkit.BlockyVending
api-version: 1.20
description: Automated chest vending machines built by players
folia-supported: true

commands:
  # No commands are used in this plugin.
